### ISSUE TITLE
throws error about gulp path

### ISSUE THREAD

**Issue by lombardi-gux** [NicoSantangelo/sublime-gulp#13]
First time I tried running plugin, I got an error that Gulp was not installed.  So, after Googling I ran
`sudo ln -s /usr/local/bin/node /usr/bin/node`  which had worked for me in other cases.

This time, the plugin ran, opened the control panel, but then when I clicked "default" in the tasks list I get:
`/bin/sh: gulp: command not found`

**Comment by alextegelid** [comment]
Sorry to bump an old issue but I'm experiencing this now. Gulp runs fine in the terminal but not from within Sublime.

Panel output:
```
Running 'default'...
/bin/sh: gulp: command not found
```

I've tried with and without this in `Gulp.sublime-settings`:
```
"exec_args": {
	"path": "/bin:/usr/bin:/usr/local/bin"
}
```
And I've had [SublimeFixMacPath](https://github.com/int3h/SublimeFixMacPath) installed for the past year or so, so that shouldn't be the problem.

I'm running OSX El Capitan 10.11.5 with Sublime Text 3 (Stable channel 3114)

![image](https://cloud.githubusercontent.com/assets/7058721/17583216/145e8eb6-5fb0-11e6-9f44-2d8dbd88d3e7.png)
![image](https://cloud.githubusercontent.com/assets/7058721/17583242/33a56f4c-5fb0-11e6-9b93-21dd974f738d.png)

**Comment by alextegelid** [comment]
I should mention that it ran just fine earlier today but stopped after a restart of Sublime Text (unrelated to Gulp)

**Comment by alextegelid** [comment]
Oh I remember now. I quit Sublime Text to se if the running tasks would be killed as well. When they weren't I killed the gulp process manually and then started Sublime Text again. And from that restart the Gulp package didn't work anymore

**Comment by NicoSantangelo** [comment]
Hello!

First of all, if you didn't gave it a try, you can use [`gulp_exit`](https://github.com/NicoSantangelo/sublime-gulp#quitting-sublime-killing-running-gulp-tasks) to kill your tasks on quit.

Going to the problem itself, it's really weird. The package doesn't do anything different with the path with or without running tasks.

Just to try something out, did you remove your `.sublime-gulp.cache` file before trying again?

**Comment by alextegelid** [comment]
Yeah, I'll probably end up with binding a key shortcut to `gulp_exit`. Thanks!

I tried removing the cache file twice, once through the remove cache command and once by manually removing the file in the terminal
