### ISSUE TITLE
Ascii characters causing errors on compile

### ISSUE THREAD

**Issue by rmwebs** [NicoSantangelo/sublime-gulp#36]
As requested, opening this in another issue.

Our gulpfile currently runs the following tasks, we're in the process if cleaning this up, and I'm going to do some testing on a fresh file as the one we've got does have a heck of a lot going on.

https://gist.github.com/rmwebs/be558374e7a7bd1ca0a6

The error output by sublime-gulp:
````
gulp-ruby-sass stderr: Error: Invalid US-ASCII character "\xE2"
````

The line it references: (it's a big ascii graphic at the top of a scss file that compiles fine on command line

````
/*╤═══╤═════╤═══╤══▒▓▓█████▓██▓▓█▓▓▓▒▒▒▓▓▓▒═══╤═════╤═══╤═════╤═══╤═════╤═══╤══╗````

**Comment by NicoSantangelo** [comment]
Sorry for the delay.

I'm having a tough time running the `gulp-ruby-sass` with sublime gulp!, so, two questions:

1. Are you still having problems with this?
2. Did you configure something in particular to run your `gulpfile` ? (I'm having problems getting sublime recognize the `Sass` gem)

I have a few new features that I want to tackle and because this seems to be a specific problem it might take me some time, but I'll try to fix this! :)
