### ISSUE TITLE
Add support for 'require-dir' approach

### ISSUE THREAD

**Issue by ISkomorokh** [NicoSantangelo/sublime-gulp#43]
It would be nice if package could work with such a `gulpfile.js`:

```javascript
// all gulp tasks are located in the ./build/tasks directory
// gulp configuration is in files in ./build directory
require('require-dir')('build/tasks');
```

[require-dir](https://github.com/aseemk/requireDir)

**Comment by NicoSantangelo** [comment]
Hello!, sorry for the delay.

Can you give me a brief example of how the structure of your project looks?

I ask because there are is a similar issue open, #35 in which I have a working local version (take a look at [this comment](https://github.com/NicoSantangelo/sublime-gulp/issues/35#issuecomment-122674559)) and I can't seem to find the problem so it would be really helpful if you can give me some more info.

Please let me know so I can see if it's a new issue or, if it's the same, how can I fix it.
Thanks!

**Comment by ISkomorokh** [comment]
Hi!
Sorry for the delay. Was busy at work.

I'm starting to use Aurelia. The proposed structure can be seen [here](https://github.com/aurelia/skeleton-navigation)

Thank you

**Comment by NicoSantangelo** [comment]
This should be working as of Version 5! (v5.0.0), the only caveat being is that if you use a `gulpfile.js` that only contains:

`require('require-dir')('build/tasks');`

The .sublime-gulp.cache will not be automatically regenerated if you make a change on any of your task files, you'll need to delete the cache (`Gulp: Delete cache`) before running `Gulp` again for it to change.
_But_ you also have the option of using `Gulp: Run arbitrary task`.

If you have any issues, please let me know ( @ mention me and I'll reopen this issue ).
