### ISSUE TITLE
Look for gulpfile elsewhere than just the root of the project

### ISSUE THREAD

**Issue by onlyskyguy** [NicoSantangelo/sublime-gulp#49]
I have a project which doesn't have a gulpfile in the root directory. Instead its in a nested directory:
ex) ProjectRoot/App/gulpfile.js

Is there a way to tell sublime-gulp the location of this gulpfile on a per project basis?

Otherwise, if I change the setting "gulpfile_paths": [], won't this break the path for other projects?

**Comment by NicoSantangelo** [comment]
Using `gulpfile_paths` won't break Sublime Gulp in other projects because it just appends the paths and searches there.

I had the idea of settings per project but I am not sure how to implement it yet, do you have any ideas?

**Comment by onlyskyguy** [comment]
Is there a way to export plugin settings into the main settings file for
sublime? I know you can set those in your project (edit project,)

**Comment by NicoSantangelo** [comment]
Not that I'm aware of, I'm afraid. I think the best you can do is:

1) Add an object for each project name on the Sublime Gulp settings with the keys you want, like

```javascript
{
   // Default settings here
    "my_project_name": {
        "setting1": 1,
        // etc
   }
}
```

2) Add a config file in the root of each project (like a `.jshintrc` file).

I think the second one could be the answer given that Sublime Gulp already writes a file to the root of each project (`.subilme-gulp.cache`). But I'm not sure.

**Comment by NicoSantangelo** [comment]
Well I'm going to go with using the `.sublime-project` files (using `Edit project`).
It might not be the optimal solution because you don't necessarily need a project to use Sublime, but I think it's best to keep the config files to a minimum.

So the idea is, you can set your Sublime Gulp settings in this order:

`"settings" object on sublime-project -> "Gulp" object inside .sublime-project (ST3 only) -> User - Gulp settings -> Default Gulp settings`

What do you think?
(I'll let you know here when is up)

**Comment by onlyskyguy** [comment]
I think that's great. For any project that you're going to open up
repeatedly and use gulp with, putting the settings in sublime project file
would take care of a nice workflow.

**Comment by NicoSantangelo** [comment]
This is up on `v5.2.0`! (sorry for the delay, I'm not having a lot of free time)
Please let me know if it works for you or if you have any other ideas or requests.

I'll close this but we can re-open it if you have any problems.

Thanks again!
