### ISSUE TITLE
Change to different gulpfile

### ISSUE THREAD

**Issue by danprime** [NicoSantangelo/sublime-gulp#51]
If a project has multiple subfolders with their own gulpfiles. 

    /Project/
         /subfolder_1/gulpfile.js
         /subfolder_2/gulpfile.js
         /subfolder_3/gulpfile.js

How can you change to a different gulp file? I've added all the subfolder paths so that when I first run gulp list tasks it asks me which gulpfile I want to run, but now I can't seem to change it to run a different gulpfile. I tried deleting the cache but that just rebuilds the task list from the gulpfile I already selected (I thought it would ask me which gulpfile I want to run).

**Comment by NicoSantangelo** [comment]
It should ask you for a gulpfile each time!

I think the problem is that you've added the `gulpfile_paths` setting to the Default Gulp settings, which are overwritten by Sublime.

Please check if your `Preferences -> Package Settings -> Gulp -> Settings - User` file still has the `gulpfile_paths` key

**Comment by danprime** [comment]
You're right, my mistake. I set it in the default settings.
